# Generated by Django 5.0.7 on 2024-07-30 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_organizer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='organizer_request',
        ),
    ]
