# Generated by Django 5.0.7 on 2024-08-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0008_remove_customuser_is_organizer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='event_joined',
            field=models.ManyToManyField(blank=True, related_name='participants', to='events.eventmodel'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_registered_event',
            field=models.BooleanField(default=False),
        ),
    ]
