# Generated by Django 5.0.7 on 2024-08-02 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_event_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_registered_event',
        ),
    ]
